/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ravintola;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 20128509
 */
public class Ravintola extends javax.swing.JFrame {

    /**
     * Creates new form Ravintola
     */
    public Ravintola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl1 = new javax.swing.JLabel();
        jlblNimi = new javax.swing.JLabel();
        jtxtNimi = new javax.swing.JTextField();
        jlblIkä = new javax.swing.JLabel();
        jtxtIka = new javax.swing.JTextField();
        jbtnIka = new javax.swing.JButton();
        jlblTervehdys = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbl1.setText("Olen ravintolan portsari.");

        jlblNimi.setText("Ole hyvä ja anna nimesi:");

        jtxtNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNimiActionPerformed(evt);
            }
        });

        jlblIkä.setText("Ole hyvä ja anna ikäsi:");

        jbtnIka.setText("Tarkista ikä");
        jbtnIka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIkaActionPerformed(evt);
            }
        });

        jlblTervehdys.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbl1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblNimi)
                            .addComponent(jlblIkä))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnIka, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jtxtNimi)
                            .addComponent(jtxtIka)))
                    .addComponent(jlblTervehdys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlbl1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNimi)
                    .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblIkä)
                    .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnIka)
                .addGap(18, 18, 18)
                .addComponent(jlblTervehdys, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNimiActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jtxtNimiActionPerformed

    private void jbtnIkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIkaActionPerformed
        // TODO add your handling code here:
        
        String nimi, viesti;
        float ika ;
        
        try {
            nimi = jtxtNimi.getText();
           
            if (nimi.length()==0){
            //if (nimi.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nimi ei voi olla tyhjä", "Virhe", JOptionPane.ERROR_MESSAGE);
            }
            
            //tai
            //String p = "([A-Za-z]).*";
            //if(!nimi.matches(p)){
            //    throw new Exception();
            //}
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain kirjaimia, kiitos. Virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        
        try {
            ika = Float.parseFloat(jtxtIka.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
            
       
        if (ika>=18){
            viesti = "Tervetuloa ravintolaan " + jtxtNimi.getText() + ", olet " + jtxtIka.getText() + " vuotta vanha.";
            jlblTervehdys.setText(viesti);
            jlblTervehdys.setForeground(Color.black);
            return;
        } else {
            jlblTervehdys.setText("Valitettavasti et voi päästä, koska olet alle 18 vuotta");
            jlblTervehdys.setForeground(Color.red);
            
        }
        
    }//GEN-LAST:event_jbtnIkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ravintola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ravintola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ravintola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ravintola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ravintola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnIka;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlblIkä;
    private javax.swing.JLabel jlblNimi;
    private javax.swing.JLabel jlblTervehdys;
    private javax.swing.JTextField jtxtIka;
    private javax.swing.JTextField jtxtNimi;
    // End of variables declaration//GEN-END:variables
}
